ERROR:2017-03-02 00:19:52,042-com.citywar.dice.db.DBPool-0 [main]
[ DBPool : DBPool ] 
java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://127.0.0.1:3306/db_citywar?characterEncoding=utf-8, username = root. Terminating connection pool. Original Exception: ------
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
------

	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:312)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	... 8 more
ERROR:2017-03-02 00:19:52,631-com.citywar.dice.db.DBManager-589[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:19:52,694-com.citywar.dice.db.DBManager-652[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:19:52,694-com.citywar.dice.db.DBManager-652[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:19:52,694-com.citywar.manager.ItemMgr-652[main]
ItemMgr reload exception:java.lang.NullPointerException 
ERROR:2017-03-02 00:19:52,710-com.citywar.BaseServer-668[main]
initialize CardMgr failed 
ERROR:2017-03-02 00:20:01,034-com.citywar.dice.db.DBPool-0 [main]
[ DBPool : DBPool ] 
java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://127.0.0.1:3306/db_citywar?characterEncoding=utf-8, username = root. Terminating connection pool. Original Exception: ------
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
------

	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:312)
	at com.citywar.dice.db.DBPool.<init>(DBPool.java:108)
	at com.citywar.dice.db.DBPoolManager.createPools(DBPoolManager.java:175)
	at com.citywar.dice.db.DBPoolManager.init(DBPoolManager.java:134)
	at com.citywar.dice.db.DBPoolManager.<init>(DBPoolManager.java:40)
	at com.citywar.dice.db.DBPoolManager.getInstance(DBPoolManager.java:62)
	at com.citywar.dice.db.DBManager.initConfig(DBManager.java:51)
	at com.citywar.GameServer.start(GameServer.java:185)
	at com.citywar.GameServer.main(GameServer.java:153)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:920)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4000)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:787)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:357)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:256)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:305)
	... 8 more
ERROR:2017-03-02 00:20:01,140-com.citywar.dice.db.DBManager-106[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:20:01,140-com.citywar.dice.db.DBManager-106[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:20:01,140-com.citywar.dice.db.DBManager-106[main]
[DataBase] 提示消息:没有可用的数据库连接池; 错误描述:null 
ERROR:2017-03-02 00:20:01,155-com.citywar.manager.ItemMgr-121[main]
ItemMgr reload exception:java.lang.NullPointerException 
ERROR:2017-03-02 00:20:01,155-com.citywar.BaseServer-121[main]
initialize CardMgr failed 
